### ISSUE TITLE
[OLS] CEPH is failing to load - using fallback version

### ISSUE THREAD

**Issue by haideriqbal** [obophenotype/cephalopod-ontology#10]
## Issue Description

The latest version of your ontology is failing to load in OLS. We are currently serving the last successful version as a fallback.

## Details

- **Ontology ID**: `ceph`
- **Status**: `FALLBACK`
- **Error Message**: 
```
Latest ontology version is failing to load, using the last successful version instead
```

## Action Required

Please investigate and fix the loading issue to ensure the latest version can be indexed correctly in OLS.

---
*This issue was automatically created by the OLS Reporting Service.*

**Comment by matentzn** [comment]
I think I fixed the issue - please reopen if I did not.

**Comment by haideriqbal** [comment]
@matentzn we are getting 403 for one of the imports hence still failing:

```
16:20:18.590 [main] DEBUG uk.ac.ebi.rdf2json.OntologyGraph - load ontology from: http://purl.obolibrary.org/obo/ceph.owl
16:20:18.591 [main] DEBUG uk.ac.ebi.rdf2json.OntologyGraph - parseRDF: Using predownloaded file for http://purl.obolibrary.org/obo/ceph.owl
16:20:18.622 [main] DEBUG uk.ac.ebi.rdf2json.OntologyGraph - import: http://purl.obolibrary.org/obo/ceph/taxonomy.owl
16:20:18.623 [main] DEBUG uk.ac.ebi.rdf2json.OntologyGraph - parseRDF: Using predownloaded file for http://purl.obolibrary.org/obo/ceph/taxonomy.owl
16:20:18.625 [main] DEBUG uk.ac.ebi.rdf2json.OntologyGraph - parseRDF: unable to use predownloaded file for http://purl.obolibrary.org/obo/ceph/taxonomy.owl
16:20:18.625 [main] ERROR uk.ac.ebi.rdf2json.OntologyGraph - parseRDF: Downloading (not predownloaded) http://purl.obolibrary.org/obo/ceph/taxonomy.owl
16:20:19.026 [main] ERROR uk.ac.ebi.rdf2json.RDF2JSON - Error processing ontology ceph: HTTP request failed with status code: 403 for URL: http://purl.obolibrary.org/obo/ceph/taxonomy.owl
```

**Comment by matentzn** [comment]
You are right, works only locally; proper fix is here: https://github.com/OBOFoundry/purl.obolibrary.org/pull/1074

Test 10 minutes after that PR was merged.

**Comment by haideriqbal** [comment]
Thanks! this will be picked up then in next release within 48 hours 👍

**Comment by matentzn** [comment]
was also merged just now :) So should be fine. Thanks for adding issues to ontologies instead of silently ignoring them, this is hugely useful; feel free to tag me on issues (on other ontologies) the community is not responding to so I can help coordinate the fixes.

**Comment by haideriqbal** [comment]
sounds good 👍 thanks for your help!

**Comment by matentzn** [comment]
Works now:

```
robot merge -I http://purl.obolibrary.org/obo/ceph.owl -o test.owl
```
